Drop TABLE IF EXISTS PedInjure;
CREATE TABLE PedInjure(
pedCrashId INTEGER NOT NULL 
    ,ped_pos      VARCHAR(46) NOT NULL
    ,ped_race     VARCHAR(15) NOT NULL
    ,pedage_grp   VARCHAR(7) NOT NULL
    ,ped_age      VARCHAR(7) NOT NULL
    ,ped_injury   VARCHAR(19) NOT NULL 
    ,ped_sex      VARCHAR(7) NOT NULL
   ,PRIMARY KEY(pedCrashId)
);
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (1, 'Non-Roadway - Parking Lot / Other','Black','25-29','29','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (2, 'Intersection Proper','White','30-39','34','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (3, 'Intersection Proper','White','60-69','61','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (4, 'Crosswalk Area','White','0-19','19','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (5, 'Travel Lane','Black','0-19','19','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (6, 'Non-Roadway - Parking Lot / Other','White','0-19','3','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (7, 'Paved Shoulder / Bike Lane / Parking Lane','Black','0-19','21','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (8, 'Travel Lane','Black','40-49','49','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (9, 'Non-Roadway - Parking Lot / Other','Black','0-19','23','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (10, 'Crosswalk Area','White','0-19','20','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (11, 'Crosswalk Area','Black','0-19','16','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (12, 'Crosswalk Area','White','60-69','60','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (13, 'Crosswalk Area','White','0-19','19','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (14, 'Travel Lane','Black','40-49','46','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (15, 'Travel Lane','Black','60-69','64','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (16, 'Non-Roadway - Parking Lot / Other','Black','40-49','46','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (17, 'Non-Roadway - Parking Lot / Other','Black','30-39','36','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (18, 'Non-Roadway - Parking Lot / Other','White','0-19','22','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (19, 'Travel Lane','White','60-69','60','K: Killed','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (20, 'Travel Lane','Black','0-19','21','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (21, 'Non-Roadway - Parking Lot / Other','White','60-69','70+','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (22, 'Travel Lane','White','0-19','17','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (23, 'Travel Lane','White','40-49','46','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (24, 'Driveway / Alley','White','30-39','38','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (25, 'Non-Roadway - Parking Lot / Other','White','60-69','70+','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (26, 'Crosswalk Area','White','60-69','60','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (27, 'Crosswalk Area','Black','60-69','68','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (28, 'Other / Unknown','Black','30-39','34','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (29, 'Non-Roadway - Parking Lot / Other','Hispanic','0-19','4','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (30, 'Paved Shoulder / Bike Lane / Parking Lane','Black','30-39','37','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (31, 'Travel Lane','Black','0-19','13','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (32, 'Crosswalk Area','Asian','25-29','28','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (33, 'Travel Lane','Black','40-49','45','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (34, 'Sidewalk / Shared Use Path / Driveway Crossing','White','0-19','24','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (35, 'Non-Roadway - Parking Lot / Other','Black','25-29','28','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (36, 'Travel Lane','White','40-49','45','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (37, 'Crosswalk Area','Black','25-29','29','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (38, 'Travel Lane','White','60-69','70+','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (39, 'Paved Shoulder / Bike Lane / Parking Lane','Black','30-39','39','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (40, 'Travel Lane','Black','25-29','25','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (41, 'Travel Lane','White','0-19','18','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (42, 'Travel Lane','Black','40-49','46','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (43, 'Other / Unknown','White','0-19','20','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (44, 'Travel Lane','White','30-39','30','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (45, 'Paved Shoulder / Bike Lane / Parking Lane','White','0-19','22','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (46, 'Crosswalk Area','White','40-49','45','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (47, 'Sidewalk / Shared Use Path / Driveway Crossing','White','0-19','23','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (48, 'Driveway / Alley','Asian','0-19','2','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (49, 'Sidewalk / Shared Use Path / Driveway Crossing','Black','0-19','21','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (50, 'Crosswalk Area','Black','0-19','19','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (51, 'Travel Lane','Black','60-69','64','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (52, 'Crosswalk Area','Asian','25-29','27','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (53, 'Travel Lane','Hispanic','60-69','0','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (54, 'Travel Lane','Black','0-19','22','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (55, 'Travel Lane','White','40-49','49','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (56, 'Travel Lane','White','0-19','19','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (57, 'Crosswalk Area','White','0-19','21','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (58, 'Travel Lane','Black','40-49','47','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (59, 'Non-Roadway - Parking Lot / Other','Black','0-19','19','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (60, 'Crosswalk Area','White','0-19','19','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (61, 'Travel Lane','Black','40-49','40','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (62, 'Crosswalk Area','White','0-19','18','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (63, 'Crosswalk Area','White','30-39','38','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (64, 'Travel Lane','Black','60-69','65','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (65, 'Crosswalk Area','White','30-39','33','K: Killed','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (66, 'Driveway / Alley','White','60-69','70+','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (67, 'Crosswalk Area','Black','0-19','18','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (68, 'Travel Lane','White','30-39','37','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (69, 'Non-Roadway - Parking Lot / Other','White','50-59','51','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (70, 'Crosswalk Area','White','0-19','20','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (71, 'Travel Lane','White','50-59','57','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (72, 'Crosswalk Area','White','0-19','21','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (73, 'Non-Roadway - Parking Lot / Other','Black','0-19','7','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (74, 'Travel Lane','White','0-19','19','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (75, 'Sidewalk / Shared Use Path / Driveway Crossing','Black','25-29','26','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (76, 'Paved Shoulder / Bike Lane / Parking Lane','Black','50-59','52','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (77, 'Crosswalk Area','White','0-19','7','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (78, 'Travel Lane','Black','60-69','Unknown','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (79, 'Non-Roadway - Parking Lot / Other','White','40-49','47','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (80, 'Travel Lane','White','50-59','57','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (81, 'Travel Lane','White','40-49','43','K: Killed','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (82, 'Crosswalk Area','Black','25-29','25','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (83, 'Crosswalk Area','Black','0-19','17','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (84, 'Travel Lane','White','25-29','28','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (85, 'Crosswalk Area','White','0-19','20','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (86, 'Crosswalk Area','Black','0-19','20','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (87, 'Paved Shoulder / Bike Lane / Parking Lane','Black','40-49','45','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (88, 'Non-Roadway - Parking Lot / Other','Black','30-39','39','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (89, 'Crosswalk Area','Unknown/Missing','30-39','30','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (90, 'Paved Shoulder / Bike Lane / Parking Lane','White','60-69','66','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (91, 'Non-Roadway - Parking Lot / Other','White','40-49','41','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (92, 'Crosswalk Area','White','25-29','27','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (93, 'Crosswalk Area','Hispanic','40-49','43','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (94, 'Travel Lane','Unknown/Missing','60-69','Unknown','C: Possible Injury','Unknown');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (95, 'Crosswalk Area','Asian','0-19','23','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (96, 'Non-Roadway - Parking Lot / Other','Black','0-19','22','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (97, 'Crosswalk Area','White','0-19','20','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (98, 'Crosswalk Area','White','0-19','24','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (99, 'Travel Lane','Black','40-49','40','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (100, 'Sidewalk / Shared Use Path / Driveway Crossing','White','40-49','40','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (101, 'Other / Unknown','Black','60-69','Unknown','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (102, 'Non-Roadway - Parking Lot / Other','White','60-69','68','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (103, 'Non-Roadway - Parking Lot / Other','White','25-29','28','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (104, 'Non-Roadway - Parking Lot / Other','Black','30-39','37','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (105, 'Non-Roadway - Parking Lot / Other','White','0-19','19','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (106, 'Crosswalk Area','White','0-19','19','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (107, 'Non-Roadway - Parking Lot / Other','White','25-29','26','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (108, 'Travel Lane','White','30-39','38','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (109, 'Non-Roadway - Parking Lot / Other','White','0-19','24','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (110, 'Travel Lane','White','60-69','70+','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (111, 'Crosswalk Area','White','0-19','13','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (112, 'Travel Lane','Black','50-59','52','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (113, 'Travel Lane','Black','0-19','7','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (114, 'Non-Roadway - Parking Lot / Other','Black','0-19','24','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (115, 'Crosswalk Area','White','0-19','20','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (116, 'Travel Lane','White','0-19','18','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (117, 'Travel Lane','Black','25-29','28','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (118, 'Travel Lane','Black','40-49','42','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (119, 'Crosswalk Area','Black','40-49','41','K: Killed','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (120, 'Non-Roadway - Parking Lot / Other','Asian','30-39','36','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (121, 'Crosswalk Area','White','0-19','21','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (122, 'Travel Lane','Black','60-69','0','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (123, 'Travel Lane','Asian','0-19','22','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (124, 'Non-Roadway - Parking Lot / Other','White','25-29','26','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (125, 'Travel Lane','White','50-59','50','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (126, 'Crosswalk Area','Hispanic','30-39','37','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (127, 'Travel Lane','White','0-19','24','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (128, 'Crosswalk Area','White','0-19','23','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (129, 'Travel Lane','White','40-49','47','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (130, 'Non-Roadway - Parking Lot / Other','Black','0-19','6','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (131, 'Travel Lane','Black','30-39','35','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (132, 'Crosswalk Area','White','60-69','0','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (133, 'Travel Lane','Black','0-19','19','K: Killed','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (134, 'Travel Lane','White','50-59','56','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (135, 'Travel Lane','White','0-19','11','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (136, 'Non-Roadway - Parking Lot / Other','White','25-29','26','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (137, 'Non-Roadway - Parking Lot / Other','Black','40-49','44','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (138, 'Travel Lane','Black','0-19','15','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (139, 'Travel Lane','White','30-39','38','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (140, 'Travel Lane','White','0-19','20','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (141, 'Non-Roadway - Parking Lot / Other','Other','30-39','30','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (142, 'Non-Roadway - Parking Lot / Other','Black','30-39','36','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (143, 'Crosswalk Area','Asian','30-39','35','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (144, 'Non-Roadway - Parking Lot / Other','Asian','40-49','47','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (145, 'Crosswalk Area','Black','25-29','28','Unknown Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (146, 'Travel Lane','White','50-59','56','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (147, 'Non-Roadway - Parking Lot / Other','White','50-59','57','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (148, 'Travel Lane','Hispanic','60-69','Unknown','Unknown Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (149, 'Crosswalk Area','Black','0-19','23','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (150, 'Non-Roadway - Parking Lot / Other','White','50-59','50','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (151, 'Crosswalk Area','White','25-29','26','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (152, 'Travel Lane','Asian','30-39','33','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (153, 'Travel Lane','White','40-49','44','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (154, 'Travel Lane','White','0-19','20','K: Killed','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (155, 'Crosswalk Area','Black','40-49','43','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (156, 'Travel Lane','Asian','30-39','39','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (157, 'Non-Roadway - Parking Lot / Other','Other','25-29','28','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (158, 'Driveway / Alley','White','0-19','11','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (159, 'Non-Roadway - Parking Lot / Other','White','25-29','26','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (160, 'Travel Lane','White','0-19','21','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (161, 'Travel Lane','White','30-39','32','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (162, 'Non-Roadway - Parking Lot / Other','Black','25-29','26','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (163, 'Travel Lane','Black','40-49','46','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (164, 'Travel Lane','White','0-19','24','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (165, 'Non-Roadway - Parking Lot / Other','Black','50-59','51','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (166, 'Travel Lane','White','30-39','38','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (167, 'Non-Roadway - Parking Lot / Other','Black','60-69','62','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (168, 'Crosswalk Area','Black','40-49','41','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (169, 'Non-Roadway - Parking Lot / Other','Black','30-39','31','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (170, 'Travel Lane','Hispanic','25-29','26','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (171, 'Non-Roadway - Parking Lot / Other','White','0-19','21','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (172, 'Travel Lane','Black','0-19','15','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (173, 'Sidewalk / Shared Use Path / Driveway Crossing','Black','60-69','62','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (174, 'Crosswalk Area','White','25-29','29','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (175, 'Travel Lane','White','0-19','18','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (176, 'Crosswalk Area','White','40-49','47','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (177, 'Non-Roadway - Parking Lot / Other','White','25-29','29','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (178, 'Travel Lane','Black','40-49','40','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (179, 'Crosswalk Area','White','0-19','21','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (180, 'Non-Roadway - Parking Lot / Other','Black','30-39','35','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (181, 'Intersection Proper','White','0-19','21','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (182, 'Non-Roadway - Parking Lot / Other','White','50-59','56','O: No Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (183, 'Crosswalk Area','White','40-49','45','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (184, 'Non-Roadway - Parking Lot / Other','Asian','0-19','21','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (185, 'Crosswalk Area','Asian','0-19','19','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (186, 'Intersection Proper','White','0-19','15','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (187, 'Driveway / Alley','White','50-59','50','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (188, 'Crosswalk Area','White','0-19','20','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (189, 'Non-Roadway - Parking Lot / Other','White','60-69','70+','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (190, 'Non-Roadway - Parking Lot / Other','White','50-59','50','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (191, 'Non-Roadway - Parking Lot / Other','White','0-19','23','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (192, 'Travel Lane','Black','60-69','62','K: Killed','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (193, 'Non-Roadway - Parking Lot / Other','Black','30-39','38','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (194, 'Non-Roadway - Parking Lot / Other','Black','60-69','70+','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (195, 'Travel Lane','Black','30-39','38','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (196, 'Crosswalk Area','White','0-19','19','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (197, 'Travel Lane','White','0-19','24','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (198, 'Crosswalk Area','Asian','30-39','30','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (199, 'Travel Lane','Black','40-49','48','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (200, 'Non-Roadway - Parking Lot / Other','Native American','50-59','56','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (201, 'Non-Roadway - Parking Lot / Other','Black','30-39','31','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (202, 'Driveway / Alley','Black','40-49','45','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (203, 'Non-Roadway - Parking Lot / Other','Black','0-19','23','Unknown Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (204, 'Non-Roadway - Parking Lot / Other','Hispanic','0-19','21','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (205, 'Non-Roadway - Parking Lot / Other','Black','40-49','45','Unknown Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (206, 'Travel Lane','Black','25-29','28','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (207, 'Travel Lane','White','30-39','37','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (208, 'Travel Lane','White','0-19','7','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (209, 'Crosswalk Area','White','40-49','45','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (210, 'Crosswalk Area','Native American','0-19','21','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (211, 'Travel Lane','White','25-29','29','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (212, 'Non-Roadway - Parking Lot / Other','White','0-19','6','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (213, 'Non-Roadway - Parking Lot / Other','Hispanic','0-19','18','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (214, 'Travel Lane','White','40-49','47','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (215, 'Crosswalk Area','White','25-29','25','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (216, 'Non-Roadway - Parking Lot / Other','White','25-29','28','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (217, 'Crosswalk Area','Black','50-59','55','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (218, 'Travel Lane','Black','0-19','20','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (219, 'Travel Lane','White','30-39','39','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (220, 'Travel Lane','White','50-59','53','K: Killed','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (221, 'Travel Lane','Black','30-39','30','K: Killed','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (222, 'Non-Roadway - Parking Lot / Other','Hispanic','0-19','1','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (223, 'Intersection Proper','Black','40-49','43','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (224, 'Crosswalk Area','White','0-19','24','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (225, 'Non-Roadway - Parking Lot / Other','White','60-69','70+','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (226, 'Crosswalk Area','Asian','25-29','25','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (227, 'Travel Lane','White','0-19','14','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (228, 'Sidewalk / Shared Use Path / Driveway Crossing','White','30-39','35','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (229, 'Travel Lane','Asian','30-39','35','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (230, 'Travel Lane','Hispanic','40-49','43','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (231, 'Non-Roadway - Parking Lot / Other','White','25-29','26','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (232, 'Crosswalk Area','White','25-29','29','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (233, 'Crosswalk Area','White','0-19','21','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (234, 'Paved Shoulder / Bike Lane / Parking Lane','Black','60-69','65','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (235, 'Non-Roadway - Parking Lot / Other','Black','40-49','41','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (236, 'Crosswalk Area','Black','60-69','64','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (237, 'Travel Lane','White','30-39','39','K: Killed','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (238, 'Travel Lane','White','60-69','70+','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (239, 'Crosswalk Area','White','0-19','21','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (240, 'Travel Lane','White','60-69','68','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (241, 'Travel Lane','Hispanic','40-49','40','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (242, 'Sidewalk / Shared Use Path / Driveway Crossing','Black','25-29','28','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (243, 'Crosswalk Area','White','0-19','19','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (244, 'Driveway / Alley','Black','0-19','20','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (245, 'Travel Lane','Black','30-39','34','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (246, 'Travel Lane','White','25-29','27','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (247, 'Non-Roadway - Parking Lot / Other','White','40-49','42','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (248, 'Crosswalk Area','White','0-19','18','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (249, 'Crosswalk Area','Asian','60-69','Unknown','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (250, 'Non-Roadway - Parking Lot / Other','Unknown/Missing','60-69','70+','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (251, 'Travel Lane','White','0-19','12','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (252, 'Travel Lane','Black','0-19','18','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (253, 'Crosswalk Area','White','0-19','20','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (254, 'Driveway / Alley','White','40-49','41','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (255, 'Driveway / Alley','White','0-19','24','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (256, 'Non-Roadway - Parking Lot / Other','Other','0-19','21','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (257, 'Travel Lane','White','50-59','56','K: Killed','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (258, 'Travel Lane','White','0-19','14','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (259, 'Sidewalk / Shared Use Path / Driveway Crossing','White','60-69','70+','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (260, 'Travel Lane','Hispanic','25-29','26','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (261, 'Travel Lane','Black','40-49','49','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (262, 'Crosswalk Area','Black','0-19','10','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (263, 'Non-Roadway - Parking Lot / Other','White','60-69','0','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (264, 'Sidewalk / Shared Use Path / Driveway Crossing','Black','30-39','35','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (265, 'Travel Lane','Black','0-19','24','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (266, 'Travel Lane','Black','25-29','25','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (267, 'Crosswalk Area','White','0-19','22','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (268, 'Sidewalk / Shared Use Path / Driveway Crossing','White','0-19','21','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (269, 'Non-Roadway - Parking Lot / Other','Other','60-69','70+','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (270, 'Driveway / Alley','White','30-39','31','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (271, 'Travel Lane','Hispanic','25-29','25','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (272, 'Sidewalk / Shared Use Path / Driveway Crossing','White','30-39','31','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (273, 'Crosswalk Area','Black','30-39','34','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (274, 'Crosswalk Area','Black','0-19','20','Unknown Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (275, 'Non-Roadway - Parking Lot / Other','Black','50-59','54','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (276, 'Travel Lane','Black','0-19','13','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (277, 'Driveway / Alley','White','30-39','34','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (278, 'Travel Lane','Black','25-29','29','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (279, 'Non-Roadway - Parking Lot / Other','White','40-49','45','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (280, 'Crosswalk Area','White','0-19','20','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (281, 'Non-Roadway - Parking Lot / Other','Black','0-19','23','Unknown Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (282, 'Crosswalk Area','White','0-19','19','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (283, 'Other / Unknown','Black','0-19','21','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (284, 'Crosswalk Area','White','0-19','20','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (285, 'Non-Roadway - Parking Lot / Other','Black','60-69','63','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (286, 'Travel Lane','Asian','30-39','39','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (287, 'Travel Lane','Black','0-19','23','K: Killed','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (288, 'Crosswalk Area','White','60-69','65','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (289, 'Travel Lane','White','0-19','19','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (290, 'Crosswalk Area','White','50-59','50','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (291, 'Non-Roadway - Parking Lot / Other','White','60-69','70+','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (292, 'Travel Lane','White','60-69','70+','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (293, 'Travel Lane','Asian','30-39','34','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (294, 'Non-Roadway - Parking Lot / Other','Black','0-19','19','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (295, 'Crosswalk Area','White','60-69','65','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (296, 'Travel Lane','White','50-59','56','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (297, 'Travel Lane','White','25-29','26','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (298, 'Crosswalk Area','White','60-69','60','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (299, 'Travel Lane','Black','25-29','29','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (300, 'Travel Lane','Black','0-19','24','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (301, 'Crosswalk Area','White','0-19','20','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (302, 'Crosswalk Area','White','25-29','29','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (303, 'Crosswalk Area','White','30-39','32','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (304, 'Crosswalk Area','Unknown/Missing','60-69','0','Unknown Injury','Unknown');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (305, 'Travel Lane','White','50-59','54','A: Disabling Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (306, 'Crosswalk Area','White','40-49','45','O: No Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (307, 'Travel Lane','White','25-29','27','K: Killed','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (308, 'Travel Lane','White','0-19','19','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (309, 'Other / Unknown','Black','0-19','20','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (310, 'Crosswalk Area','White','50-59','53','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (311, 'Non-Roadway - Parking Lot / Other','White','30-39','30','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (312, 'Travel Lane','Black','40-49','43','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (313, 'Travel Lane','Black','0-19','17','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (314, 'Travel Lane','Black','0-19','13','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (315, 'Crosswalk Area','White','25-29','28','C: Possible Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (316, 'Travel Lane','Black','0-19','23','B: Evident Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (317, 'Crosswalk Area','Black','0-19','21','A: Disabling Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (318, 'Non-Roadway - Parking Lot / Other','White','40-49','46','C: Possible Injury','Male');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (319, 'Non-Roadway - Parking Lot / Other','White','40-49','46','B: Evident Injury','Female');
INSERT INTO PedInjure(pedCrashId,ped_pos,ped_race,pedage_grp,ped_age,ped_injury,ped_sex) VALUES (320, 'Travel Lane','Hispanic','40-49','43','K: Killed','Male');
